/* Generated by Yosys 0.65 (git sha1 aec814bdf3071f7e0fd0fbe43f7f711e99d01e24, clang++ 21.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:24.1-75.10" *)
module ternary_mac_array(clk, rst, act_in, wt_in, valid_in, valid_out, acc_out);
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:29.35-29.38" *)
  input clk;
  wire clk;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:30.35-30.38" *)
  input rst;
  wire rst;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:33.37-33.43" *)
  input [7:0] act_in;
  wire [7:0] act_in;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:34.37-34.42" *)
  input [1:0] wt_in;
  wire [1:0] wt_in;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:37.35-37.43" *)
  input valid_in;
  wire valid_in;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:38.35-38.44" *)
  output valid_out;
  reg valid_out;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:41.37-41.44" *)
  output [31:0] acc_out;
  wire [31:0] acc_out;
  wire _000_;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:68.27-68.36" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:64.26-64.53|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _199_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:64.26-64.53|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _200_;
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:45.30-45.33" *)
  reg [31:0] acc;
  assign _196_ = act_in[7] | _194_;
  assign _197_ = wt_in[0] & _196_;
  assign _198_ = _195_ & _197_;
  assign _002_ = ~(acc[30] & _198_);
  assign _003_ = ~(acc[30] ^ _198_);
  assign _004_ = ~(acc[29] & _198_);
  assign _005_ = acc[29] | _198_;
  assign _006_ = ~(acc[28] & _198_);
  assign _007_ = ~(acc[28] ^ _198_);
  assign _008_ = ~(acc[27] & _198_);
  assign _009_ = acc[27] | _198_;
  assign _010_ = ~(acc[26] & _198_);
  assign _011_ = ~(acc[26] ^ _198_);
  assign _012_ = ~(acc[25] & _198_);
  assign _013_ = acc[25] | _198_;
  assign _014_ = ~(acc[24] & _198_);
  assign _015_ = ~(acc[21] | acc[20]);
  assign _016_ = ~(acc[23] | acc[22]);
  assign _017_ = ~(_015_ & _016_);
  assign _018_ = ~(_198_ & _017_);
  assign _019_ = ~(acc[20] & _198_);
  assign _020_ = ~(acc[20] ^ _198_);
  assign _021_ = ~(acc[19] & _198_);
  assign _022_ = acc[19] | _198_;
  assign _023_ = ~(acc[18] & _198_);
  assign _024_ = ~(acc[18] ^ _198_);
  assign _025_ = ~(acc[17] & _198_);
  assign _026_ = acc[17] | _198_;
  assign _027_ = ~(acc[16] & _198_);
  assign _028_ = ~(acc[16] ^ _198_);
  assign _029_ = acc[15] | _198_;
  assign _030_ = ~(acc[15] & _198_);
  assign _031_ = ~(acc[14] & _198_);
  assign _032_ = ~(acc[14] ^ _198_);
  assign _033_ = ~(acc[13] & _198_);
  assign _034_ = acc[13] | _198_;
  assign _035_ = ~(acc[12] & _198_);
  assign _036_ = ~(acc[12] ^ _198_);
  assign _037_ = acc[11] | _198_;
  assign _038_ = ~(acc[11] & _198_);
  assign _039_ = ~(acc[10] & _198_);
  assign _040_ = ~(acc[10] ^ _198_);
  assign _041_ = ~(acc[9] & _198_);
  assign _042_ = acc[9] | _198_;
  assign _043_ = ~(acc[8] & _198_);
  assign _044_ = ~(acc[7] & _198_);
  assign _045_ = ~(acc[7] ^ _198_);
  assign _046_ = ~(act_in[6] ^ _192_);
  assign _047_ = wt_in[0] & _046_;
  assign _048_ = ~(acc[6] & _047_);
  assign _049_ = ~(acc[6] ^ _047_);
  assign _050_ = ~(act_in[5] ^ _190_);
  assign _051_ = wt_in[0] & _050_;
  assign _052_ = ~(acc[5] & _051_);
  assign _053_ = acc[5] | _051_;
  assign _054_ = ~(act_in[4] ^ _188_);
  assign _055_ = wt_in[0] & _054_;
  assign _056_ = ~(acc[4] & _055_);
  assign _057_ = ~(acc[4] ^ _055_);
  assign _058_ = ~(act_in[3] ^ _186_);
  assign _059_ = wt_in[0] & _058_;
  assign _060_ = ~(acc[3] & _059_);
  assign _061_ = acc[3] | _059_;
  assign _062_ = act_in[2] ^ _184_;
  assign _063_ = wt_in[0] & _062_;
  assign _064_ = ~(acc[2] & _063_);
  assign _065_ = act_in[1] | ~(_182_);
  assign _066_ = _179_ | _183_;
  assign _067_ = wt_in[0] & _066_;
  assign _068_ = _065_ & _067_;
  assign _069_ = ~(acc[1] & _068_);
  assign _070_ = ~(acc[1] ^ _068_);
  assign _071_ = _181_ | _070_;
  assign _072_ = _069_ & _071_;
  assign _073_ = ~(acc[2] ^ _063_);
  assign _074_ = _072_ | _073_;
  assign _075_ = ~(_064_ & _074_);
  assign _076_ = ~(_061_ & _075_);
  assign _077_ = _060_ & _076_;
  assign _078_ = _057_ | _077_;
  assign _079_ = ~(_056_ & _078_);
  assign _080_ = ~(_053_ & _079_);
  assign _081_ = _052_ & _080_;
  assign _082_ = _049_ | _081_;
  assign _083_ = _048_ & _082_;
  assign _084_ = _045_ | _083_;
  assign _085_ = _044_ & _084_;
  assign _086_ = ~(acc[8] ^ _198_);
  assign _087_ = _085_ | _086_;
  assign _088_ = ~(_043_ & _087_);
  assign _089_ = ~(_042_ & _088_);
  assign _090_ = _041_ & _089_;
  assign _091_ = _040_ | _090_;
  assign _092_ = _039_ & _091_;
  assign _093_ = ~(_038_ & _092_);
  assign _094_ = ~(_037_ & _093_);
  assign _095_ = _036_ | _094_;
  assign _096_ = ~(_035_ & _095_);
  assign _097_ = ~(_034_ & _096_);
  assign _098_ = _033_ & _097_;
  assign _099_ = _032_ | _098_;
  assign _100_ = _031_ & _099_;
  assign _101_ = ~(_030_ & _100_);
  assign _102_ = ~(_029_ & _101_);
  assign _103_ = _028_ | _102_;
  assign _104_ = ~(_027_ & _103_);
  assign _105_ = ~(_026_ & _104_);
  assign _106_ = _025_ & _105_;
  assign _107_ = _024_ | _106_;
  assign _108_ = ~(_023_ & _107_);
  assign _109_ = ~(_022_ & _108_);
  assign _110_ = ~(_021_ & _109_);
  assign _111_ = _020_ | ~(_110_);
  assign _112_ = ~(acc[21] ^ _198_);
  assign _113_ = _111_ | _112_;
  assign _114_ = ~(acc[22] & _198_);
  assign _115_ = ~(acc[22] ^ _198_);
  assign _116_ = ~(acc[23] ^ _198_);
  assign _117_ = _115_ | _116_;
  assign _118_ = _113_ | _117_;
  assign _119_ = _018_ & _118_;
  assign _120_ = ~(acc[24] ^ _198_);
  assign _121_ = _119_ | _120_;
  assign _122_ = ~(_014_ & _121_);
  assign _123_ = ~(_013_ & _122_);
  assign _124_ = _012_ & _123_;
  assign _125_ = _011_ | _124_;
  assign _126_ = ~(_010_ & _125_);
  assign _127_ = ~(_009_ & _126_);
  assign _128_ = _008_ & _127_;
  assign _129_ = _007_ | _128_;
  assign _130_ = ~(_006_ & _129_);
  assign _131_ = ~(_005_ & _130_);
  assign _132_ = _004_ & _131_;
  assign _133_ = _003_ | _132_;
  assign _134_ = ~(_002_ & _133_);
  assign _135_ = ~(acc[31] ^ _198_);
  assign _200_[31] = ~(_134_ ^ _135_);
  assign _200_[30] = _003_ ^ _132_;
  assign _136_ = ~(_004_ & _005_);
  assign _200_[29] = ~(_130_ ^ _136_);
  assign _200_[28] = _007_ ^ _128_;
  assign _137_ = ~(_008_ & _009_);
  assign _200_[27] = ~(_126_ ^ _137_);
  assign _200_[26] = _011_ ^ _124_;
  assign _138_ = ~(_012_ & _013_);
  assign _200_[25] = ~(_122_ ^ _138_);
  assign _200_[24] = _119_ ^ _120_;
  assign _139_ = _015_ | ~(_198_);
  assign _140_ = _113_ & _139_;
  assign _141_ = _115_ | _140_;
  assign _142_ = ~(_114_ & _141_);
  assign _200_[23] = ~(_116_ ^ _142_);
  assign _200_[22] = _115_ ^ _140_;
  assign _143_ = ~(_019_ & _111_);
  assign _200_[21] = ~(_112_ ^ _143_);
  assign _200_[20] = ~(_020_ ^ _110_);
  assign _144_ = ~(_021_ & _022_);
  assign _200_[19] = ~(_108_ ^ _144_);
  assign _200_[18] = _024_ ^ _106_;
  assign _145_ = ~(_025_ & _026_);
  assign _200_[17] = ~(_104_ ^ _145_);
  assign _200_[16] = _028_ ^ _102_;
  assign _146_ = _029_ & _030_;
  assign _200_[15] = ~(_100_ ^ _146_);
  assign _200_[14] = _032_ ^ _098_;
  assign _147_ = ~(_033_ & _034_);
  assign _200_[13] = ~(_096_ ^ _147_);
  assign _200_[12] = _036_ ^ _094_;
  assign _148_ = _037_ & _038_;
  assign _200_[11] = ~(_092_ ^ _148_);
  assign _200_[10] = _040_ ^ _090_;
  assign _149_ = ~(_041_ & _042_);
  assign _200_[9] = ~(_088_ ^ _149_);
  assign _200_[8] = _085_ ^ _086_;
  assign _200_[7] = _045_ ^ _083_;
  assign _200_[6] = _049_ ^ _081_;
  assign _150_ = ~(_052_ & _053_);
  assign _200_[5] = ~(_079_ ^ _150_);
  assign _200_[4] = _057_ ^ _077_;
  assign _151_ = ~(_060_ & _061_);
  assign _200_[3] = ~(_075_ ^ _151_);
  assign _200_[2] = _072_ ^ _073_;
  assign _200_[1] = _181_ ^ _070_;
  assign _000_ = rst | valid_in;
  assign _152_ = ~(acc[26] | acc[25]);
  assign _153_ = ~(acc[6] | acc[5]);
  assign _154_ = _152_ & _153_;
  assign _155_ = ~(acc[1] | acc[11]);
  assign _156_ = ~(acc[31] | acc[27]);
  assign _157_ = _155_ & _156_;
  assign _158_ = ~(acc[0] | acc[12]);
  assign _159_ = ~(acc[4] | acc[7]);
  assign _160_ = _158_ & _159_;
  assign _161_ = ~(acc[28] | acc[10]);
  assign _162_ = ~(acc[15] | acc[13]);
  assign _163_ = _161_ & _162_;
  assign _164_ = _160_ & _163_;
  assign _165_ = ~(acc[19] | acc[9]);
  assign _166_ = ~(acc[18] | acc[3]);
  assign _167_ = _165_ & _166_;
  assign _168_ = ~(acc[30] | acc[17]);
  assign _169_ = ~(acc[2] | acc[8]);
  assign _170_ = _168_ & _169_;
  assign _171_ = _167_ & _170_;
  assign _172_ = _157_ & ~(acc[16]);
  assign _173_ = _164_ & _172_;
  assign _174_ = ~(acc[14] | acc[29]);
  assign _175_ = _174_ & ~(acc[24]);
  assign _176_ = ~(_154_ & _175_);
  assign _177_ = ~(_017_ | _176_);
  assign _178_ = _171_ & _177_;
  assign _001_ = ~(_173_ & _178_);
  assign _179_ = ~act_in[0];
  assign _180_ = act_in[0] & wt_in[0];
  assign _181_ = ~(acc[0] & _180_);
  assign _199_[0] = acc[0] ^ _180_;
  assign _182_ = ~(act_in[0] & wt_in[1]);
  assign _183_ = ~(act_in[1] & wt_in[1]);
  assign _184_ = ~(_182_ & _183_);
  assign _185_ = act_in[2] | _184_;
  assign _186_ = ~(wt_in[1] & _185_);
  assign _187_ = act_in[3] | _185_;
  assign _188_ = ~(wt_in[1] & _187_);
  assign _189_ = act_in[4] | _187_;
  assign _190_ = ~(wt_in[1] & _189_);
  assign _191_ = act_in[5] | _189_;
  assign _192_ = ~(wt_in[1] & _191_);
  assign _193_ = act_in[6] | _191_;
  assign _194_ = wt_in[1] & _193_;
  assign _195_ = ~(act_in[7] & _194_);
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[0] <= 1'h0;
    else if (valid_in) acc[0] <= _199_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[1] <= 1'h0;
    else if (valid_in) acc[1] <= _200_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[2] <= 1'h0;
    else if (valid_in) acc[2] <= _200_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[3] <= 1'h0;
    else if (valid_in) acc[3] <= _200_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[4] <= 1'h0;
    else if (valid_in) acc[4] <= _200_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[5] <= 1'h0;
    else if (valid_in) acc[5] <= _200_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[6] <= 1'h0;
    else if (valid_in) acc[6] <= _200_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[7] <= 1'h0;
    else if (valid_in) acc[7] <= _200_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[8] <= 1'h0;
    else if (valid_in) acc[8] <= _200_[8];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[9] <= 1'h0;
    else if (valid_in) acc[9] <= _200_[9];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[10] <= 1'h0;
    else if (valid_in) acc[10] <= _200_[10];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[11] <= 1'h0;
    else if (valid_in) acc[11] <= _200_[11];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[12] <= 1'h0;
    else if (valid_in) acc[12] <= _200_[12];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[13] <= 1'h0;
    else if (valid_in) acc[13] <= _200_[13];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[14] <= 1'h0;
    else if (valid_in) acc[14] <= _200_[14];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[15] <= 1'h0;
    else if (valid_in) acc[15] <= _200_[15];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[16] <= 1'h0;
    else if (valid_in) acc[16] <= _200_[16];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[17] <= 1'h0;
    else if (valid_in) acc[17] <= _200_[17];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[18] <= 1'h0;
    else if (valid_in) acc[18] <= _200_[18];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[19] <= 1'h0;
    else if (valid_in) acc[19] <= _200_[19];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[20] <= 1'h0;
    else if (valid_in) acc[20] <= _200_[20];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[21] <= 1'h0;
    else if (valid_in) acc[21] <= _200_[21];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[22] <= 1'h0;
    else if (valid_in) acc[22] <= _200_[22];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[23] <= 1'h0;
    else if (valid_in) acc[23] <= _200_[23];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[24] <= 1'h0;
    else if (valid_in) acc[24] <= _200_[24];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[25] <= 1'h0;
    else if (valid_in) acc[25] <= _200_[25];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[26] <= 1'h0;
    else if (valid_in) acc[26] <= _200_[26];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[27] <= 1'h0;
    else if (valid_in) acc[27] <= _200_[27];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[28] <= 1'h0;
    else if (valid_in) acc[28] <= _200_[28];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[29] <= 1'h0;
    else if (valid_in) acc[29] <= _200_[29];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[30] <= 1'h0;
    else if (valid_in) acc[30] <= _200_[30];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (rst) acc[31] <= 1'h0;
    else if (valid_in) acc[31] <= _200_[31];
  (* \always_ff  = 32'd1 *)
  (* src = "/Users/manafalali/Desktop/ECE410/.claude/worktrees/compassionate-brahmagupta-5a57bd/codefest/cf07/hdl/synth_top.sv:59.5-71.8" *)
  always @(posedge clk)
    if (_000_) valid_out <= 1'h0;
    else valid_out <= _001_;
  assign _200_[0] = _199_[0];
  assign acc_out = acc;
endmodule
