// mac_llm_B.v — Generated by GPT-4o (gpt-4o-2024-11-20)
// Prompt: MAC module, clk/rst/a[7:0]/b[7:0]->out[31:0], synchronous active-high reset,
//         out += a*b each cycle, synthesizable SystemVerilog, always_ff only.

module mac (
    input  wire                 clk,   // NOTE: 'wire' is Verilog-style, not SystemVerilog 'logic'
    input  wire                 rst,
    input  wire signed [7:0]    a,
    input  wire signed [7:0]    b,
    output reg  signed [31:0]   out    // NOTE: 'reg' is Verilog-style, not SystemVerilog 'logic'
);
    wire signed [15:0] product;
    assign product = a * b;            // 16-bit intermediate — sign extension to 32-bit missing

    always @(posedge clk) begin        // BUG: 'always' not 'always_ff' as spec requires
        if (rst)
            out <= 32'sd0;
        else
            out <= out + product;      // adding 16-bit signed to 32-bit signed: implicit extension
    end
endmodule
