// mac_llm_A.v — Generated by Claude Sonnet 4.6
// Prompt: MAC module, clk/rst/a[7:0]/b[7:0]->out[31:0], synchronous active-high reset,
//         out += a*b each cycle, synthesizable SystemVerilog, always_ff only.

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic [7:0]  a,       // BUG: missing 'signed' — treated as unsigned
    input  logic [7:0]  b,       // BUG: missing 'signed' — treated as unsigned
    output logic signed [31:0] out
);
    always_ff @(posedge clk) begin
        if (rst)
            out <= 32'sd0;
        else
            // Manual sign extension workaround because ports are not signed.
            // Verbose and fragile — a[7] and b[7] are sign bits of the original values.
            out <= out + ({{16{a[7]}}, a} * {{16{b[7]}}, b});
    end
endmodule
