// crossbar_mac.sv
// CF06 CLLM — Binary-weight crossbar MAC
// ECE 410/510 Spring 2026
//
// Computes out[j] = sum_i (weight[i][j] * in[i])
// Weights are binary: +1 or -1 (encoded: 0 = +1, 1 = -1)
// Specialised for N=4 inputs, M=4 outputs, DATA_W=8, ACC_W=32
//
// Generated by Claude Sonnet 4.6 (LLM-assisted)

module crossbar_mac #(
    parameter N      = 4,
    parameter M      = 4,
    parameter DATA_W = 8,
    parameter ACC_W  = 32
)(
    input  wire                    clk,
    input  wire                    rst,
    // weight flat: bit [i*M+j] = weight[i][j], 0=+1, 1=-1
    input  wire  [N*M-1:0]        weight,
    // input vector, flat: bits [(i+1)*DATA_W-1 : i*DATA_W] = in[i]
    input  wire  [N*DATA_W-1:0]   in_vec,
    input  wire                    valid_in,
    // output vector, flat: bits [(j+1)*ACC_W-1 : j*ACC_W] = out[j]
    output reg   [M*ACC_W-1:0]    out_vec,
    output reg                     valid_out
);

    // Sign-extend helper: pick in[i] as signed
    function signed [ACC_W-1:0] get_in;
        input integer i;
        reg signed [DATA_W-1:0] v;
        begin
            v = in_vec[i*DATA_W +: DATA_W];
            get_in = {{(ACC_W-DATA_W){v[DATA_W-1]}}, v};
        end
    endfunction

    integer i, j;
    reg signed [ACC_W-1:0] acc [0:M-1];

    always @(posedge clk) begin
        if (rst) begin
            for (j = 0; j < M; j = j+1)
                out_vec[j*ACC_W +: ACC_W] <= {ACC_W{1'b0}};
            valid_out <= 1'b0;
        end else if (valid_in) begin
            for (j = 0; j < M; j = j+1) begin
                acc[j] = {ACC_W{1'b0}};
                for (i = 0; i < N; i = i+1) begin
                    if (weight[i*M + j] == 1'b0)
                        acc[j] = acc[j] + get_in(i);
                    else
                        acc[j] = acc[j] - get_in(i);
                end
                out_vec[j*ACC_W +: ACC_W] <= acc[j];
            end
            valid_out <= 1'b1;
        end else begin
            valid_out <= 1'b0;
        end
    end

endmodule
