SIM              = icarus
TOPLEVEL_LANG    = verilog
VERILOG_SOURCES  = $(PWD)/../hdl/mac_correct.v
TOPLEVEL         = mac
COCOTB_TEST_MODULES = test_mac

include $(shell cocotb-config --makefiles)/Makefile.sim
